/**
 * Google Gemini API Client
 *
 * Provides easy-to-use functions for interacting with Google's Gemini 3 Pro API.
 * Supports text generation, multimodal (image) inputs, and structured JSON outputs.
 */

// Dev-only test feature - Gemini API integration
const GEMINI_API_KEY = process.env.EXPO_PUBLIC_GOOGLE_API_KEY || process.env.EXPO_PUBLIC_VIBECODE_GOOGLE_API_KEY;
const GEMINI_ENDPOINT = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-preview:generateContent';

if (!GEMINI_API_KEY && __DEV__) {
  console.warn('[Gemini] API key not found. This is a dev-only test feature.');
}

/**
 * Content part types for Gemini API
 */
type TextPart = {
  text: string;
};

type InlineDataPart = {
  inline_data: {
    mime_type: string;
    data: string; // Base64 encoded
  };
};

type ContentPart = TextPart | InlineDataPart;

/**
 * Message in a conversation
 */
type Message = {
  role: 'user' | 'model';
  parts: ContentPart[];
};

/**
 * Generation configuration
 */
type GenerationConfig = {
  temperature?: number; // 0.0-2.0, default 1.0
  topP?: number; // 0.0-1.0, default 0.95
  topK?: number; // 1-40, default 40
  maxOutputTokens?: number;
  stopSequences?: string[];
  responseMimeType?: 'text/plain' | 'application/json';
  responseSchema?: object; // Required if responseMimeType is 'application/json'
  thinking_level?: 'low' | 'high'; // 'low' for faster, 'high' for maximum reasoning
};

/**
 * Gemini API request body
 */
type GeminiRequest = {
  contents: Message[];
  system_instruction?: {
    parts: TextPart[];
  };
  generationConfig?: GenerationConfig;
  safetySettings?: any[];
  tools?: any[];
};

/**
 * Gemini API response
 */
type GeminiResponse = {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
    finishReason?: string;
  }>;
  promptFeedback?: {
    blockReason?: string;
  };
  error?: {
    code: number;
    message: string;
    status: string;
  };
};

/**
 * Generate text using Gemini 3 Pro
 *
 * @param prompt - The text prompt to send to Gemini
 * @param options - Optional generation configuration
 * @returns Generated text response
 *
 * @example
 * ```typescript
 * const response = await generateText('What is artificial intelligence?');
 * console.log(response);
 * ```
 */
export async function generateText(
  prompt: string,
  options?: GenerationConfig
): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured. Please add GOOGLE-GEMINI integration.');
  }

  const requestBody: GeminiRequest = {
    contents: [{
      role: 'user',
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      temperature: 1.0, // Default recommended by Gemini
      ...options,
    }
  };

  try {
    const response = await fetch(GEMINI_ENDPOINT, {
      method: 'POST',
      headers: {
        'x-goog-api-key': GEMINI_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`);
    }

    const data: GeminiResponse = await response.json();

    // Check for API-level errors
    if (data.error) {
      throw new Error(`Gemini API error: ${data.error.message}`);
    }

    // Check if content was blocked
    if (data.promptFeedback?.blockReason) {
      throw new Error(`Content blocked: ${data.promptFeedback.blockReason}`);
    }

    // Extract text from response
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new Error('No text generated by Gemini');
    }

    return text;
  } catch (error: any) {
    console.error('[Gemini] Generation failed:', error);
    throw error;
  }
}

/**
 * Generate structured JSON output using Gemini 3 Pro
 *
 * @param prompt - The text prompt to send to Gemini
 * @param schema - JSON schema defining the expected output structure
 * @param options - Optional generation configuration
 * @returns Parsed JSON object matching the schema
 *
 * @example
 * ```typescript
 * const result = await generateJSON(
 *   'Analyze this review: "Great product, fast shipping!"',
 *   {
 *     type: 'object',
 *     properties: {
 *       sentiment: { type: 'string' },
 *       score: { type: 'number' }
 *     }
 *   }
 * );
 * console.log(result.sentiment); // "positive"
 * ```
 */
export async function generateJSON<T = any>(
  prompt: string,
  schema: object,
  options?: Omit<GenerationConfig, 'responseMimeType' | 'responseSchema'>
): Promise<T> {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured. Please add GOOGLE-GEMINI integration.');
  }

  const requestBody: GeminiRequest = {
    contents: [{
      role: 'user',
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      temperature: 1.0,
      ...options,
      responseMimeType: 'application/json',
      responseSchema: schema,
    }
  };

  try {
    const response = await fetch(GEMINI_ENDPOINT, {
      method: 'POST',
      headers: {
        'x-goog-api-key': GEMINI_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`);
    }

    const data: GeminiResponse = await response.json();

    if (data.error) {
      throw new Error(`Gemini API error: ${data.error.message}`);
    }

    const jsonText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!jsonText) {
      throw new Error('No JSON generated by Gemini');
    }

    return JSON.parse(jsonText) as T;
  } catch (error: any) {
    console.error('[Gemini] JSON generation failed:', error);
    throw error;
  }
}

/**
 * Have a multi-turn conversation with Gemini 3 Pro
 *
 * @param messages - Array of conversation messages
 * @param systemInstruction - Optional system instruction to guide behavior
 * @param options - Optional generation configuration
 * @returns Generated text response
 *
 * @example
 * ```typescript
 * const response = await chat([
 *   { role: 'user', parts: [{ text: 'Hello!' }] },
 *   { role: 'model', parts: [{ text: 'Hi! How can I help?' }] },
 *   { role: 'user', parts: [{ text: 'Tell me a joke' }] }
 * ]);
 * ```
 */
export async function chat(
  messages: Message[],
  systemInstruction?: string,
  options?: GenerationConfig
): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured. Please add GOOGLE-GEMINI integration.');
  }

  const requestBody: GeminiRequest = {
    contents: messages,
    generationConfig: {
      temperature: 1.0,
      ...options,
    }
  };

  if (systemInstruction) {
    requestBody.system_instruction = {
      parts: [{ text: systemInstruction }]
    };
  }

  try {
    const response = await fetch(GEMINI_ENDPOINT, {
      method: 'POST',
      headers: {
        'x-goog-api-key': GEMINI_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`);
    }

    const data: GeminiResponse = await response.json();

    if (data.error) {
      throw new Error(`Gemini API error: ${data.error.message}`);
    }

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new Error('No text generated by Gemini');
    }

    return text;
  } catch (error: any) {
    console.error('[Gemini] Chat failed:', error);
    throw error;
  }
}

/**
 * Analyze an image with text prompt using Gemini 3 Pro
 *
 * @param prompt - Text prompt describing what to analyze
 * @param imageBase64 - Base64-encoded image data
 * @param mimeType - Image MIME type (e.g., 'image/jpeg', 'image/png')
 * @param options - Optional generation configuration
 * @returns Generated text response
 *
 * @example
 * ```typescript
 * const description = await analyzeImage(
 *   'Describe what you see in this image',
 *   base64ImageData,
 *   'image/jpeg'
 * );
 * ```
 */
export async function analyzeImage(
  prompt: string,
  imageBase64: string,
  mimeType: string = 'image/jpeg',
  options?: GenerationConfig
): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured. Please add GOOGLE-GEMINI integration.');
  }

  const requestBody: GeminiRequest = {
    contents: [{
      role: 'user',
      parts: [
        { text: prompt },
        { inline_data: { mime_type: mimeType, data: imageBase64 } }
      ]
    }],
    generationConfig: {
      temperature: 1.0,
      ...options,
    }
  };

  try {
    const response = await fetch(GEMINI_ENDPOINT, {
      method: 'POST',
      headers: {
        'x-goog-api-key': GEMINI_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`);
    }

    const data: GeminiResponse = await response.json();

    if (data.error) {
      throw new Error(`Gemini API error: ${data.error.message}`);
    }

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new Error('No text generated by Gemini');
    }

    return text;
  } catch (error: any) {
    console.error('[Gemini] Image analysis failed:', error);
    throw error;
  }
}
